[package]
name = "streamlit_startup_script"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
toml = "0.8.19"
chrono = "0.4.38"
log = "0.4.22"
simplelog = "0.12.2"
